name: Continuous Integration
# copied from:
# https://github.com/allyourcodebase/AFLplusplus/blob/main/.github/workflows/ci.yaml
on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up LLVM and Clang
        run: |
          sudo apt-get update
          sudo apt-get install -y lld llvm llvm-dev clang

      - name: Set up Zig
        uses: mlugg/setup-zig@v1

      - name: Run `build`
        run: zig build
