name: Continuous Integration
# copied from:
# https://github.com/allyourcodebase/AFLplusplus/blob/main/.github/workflows/ci.yaml
on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Zig
        uses: mlugg/setup-zig@v1

      - name: Check fmt
        run: zig build -Dfmtcheck fmt
  
      - name: Run `build`
        run: zig build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zig-out
          path: zig-out
          retention-days: 14